# -*- coding: utf-8 -*-
"""Kimyasal Veri Analizi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19ibXazse3aNY8uQLlGf4K6zn6hDKl7Tc
"""

import openpyxl
import pandas as pd

# Excel dosyasının yolu
excel_dosya="DeşarjStandartları.xlsx"

# Atıksu tipini kullanıcıdan al
atiksu_tipi=input("Atıksu tipini girin: ")

# Excel dosyasını oku
excel_data=pd.ExcelFile(excel_dosya)

# Bütün sayfa isimlerini al
sayfa_listesi=excel_data.sheet_names

# Atıksu tipine uygun olan sayfayı bul
bulunan_sayfa=None
for sayfa in sayfa_listesi:
    if atiksu_tipi.lower() in sayfa.lower():
        bulunan_sayfa=sayfa
        break

if bulunan_sayfa is None:
    print("Atıksu tipi için uygun sayfa bulunamadı.")
else:
    # Sayfayı DataFrame olarak oku
    df=excel_data.parse(sheet_name=bulunan_sayfa)

    # Tabloyu göster
    print("Tablo:")
    print(df)

    # Parametre değerlerini sor ve değerlendir
    for index, row in df.iterrows():
        parametre = row["Parametre"]
        deger=input(f"{parametre} değerinizi girin: ")

        if float(deger)>row["2 saatlik kompozit numune"]:
            print("Atıksu deşarja uygun değil.")
            break
        else:
            print("Atıksu deşarja uygun.")